### ISSUE TITLE
No module named 'HT_opp'

### ISSUE THREAD

**Issue by mwaliman** [ReubenDo/InExtremIS#1]
Hi, I've seemingly successfully followed the install instructions and am trying to run the first example provided in the readme for running the training file but run into the following error.

`
python3 train.py --model_dir ./models/simulated_gradient_eucl_deep_crf/ --alpha 15 --beta 0.05 --weight_crf 0.0001 --mode extreme_points --label_postfix Extremes --img_gradient_postfix Sobel --path_data data/T2/ --path_labels data/extreme_points/simulated/ --with_euclidean --with_prob
Traceback (most recent call last):
  File "train.py", line 37, in <module>
    from ScribbleDA.scribbleDALoss import CRFLoss 
  File "/home/mwaliman/workspace/InExtremIS/ScribbleDA/scribbleDALoss.py", line 5, in <module>
    from .Permutohedral_attention_module.PAM_cuda.pl import PermutohedralLattice as pl
  File "/home/mwaliman/workspace/InExtremIS/ScribbleDA/Permutohedral_attention_module/PAM_cuda/pl.py", line 5, in <module>
    import HT_opp
ModuleNotFoundError: No module named 'HT_opp'
`

I haven't encountered other errors during setup and tried to look for the HT_opp module but haven't been successful. Do you have an idea how to proceed?

Thank you!

**Comment by ReubenDo** [comment]
Hi @mwaliman,

It seems that the CUDA implementation of the permutohedral lattice hasn't been successfully installed. 

What are the logs when you are installing it?
```
cd ScribbleDA/Permutohedral_attention_module/PAM_cuda/
python3 setup.py build
python3 setup.py install --user
```

Regards,
Reuben

**Comment by mwaliman** [comment]
Hi Reuben, thank for getting back to me. These are the logs when I install Permutohedral_attention_module

`python3 setup.py build
`
> /home/mwaliman/workspace/InExtremIS/env/lib/python3.6/site-packages/torch/utils/cpp_extension.py:352: UserWarning: Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils backend.
  warnings.warn(msg.format('we could not find ninja.'))

and 

`python3 setup.py install --user
`

>  Checking .pth file support in /home/mwaliman/.local/lib/python3.6/site-packages/
> /home/mwaliman/workspace/InExtremIS/env/bin/python3 -E -c pass
> TEST FAILED: /home/mwaliman/.local/lib/python3.6/site-packages/ does NOT support .pth files
> bad install directory or PYTHONPATH
> 
> You are attempting to install a package to a directory that is not
> on PYTHONPATH and which Python does not read ".pth" files from.  The
> installation directory you specified (via --install-dir, --prefix, or
> the distutils default setting) was:
> 
>     /home/mwaliman/.local/lib/python3.6/site-packages/
> 
> and your PYTHONPATH environment variable currently contains:
> 
>     ''
> 
> Here are some of your options for correcting the problem:
> 
> * You can choose a different installation directory, i.e., one that is
>   on PYTHONPATH or supports .pth files
> 
> * You can add the installation directory to the PYTHONPATH environment
>   variable.  (It must then also be on PYTHONPATH whenever you run
>   Python and want to use the package(s) you are installing.)
> 
> * You can set up the installation directory to support ".pth" files by
>   using one of the approaches described here:
> 
>   https://setuptools.readthedocs.io/en/latest/easy_install.html#custom-installation-locations
> 
> 
> Please make the appropriate changes for your system and try again.
> running bdist_egg
> running egg_info
> writing extensions.egg-info/PKG-INFO
> writing dependency_links to extensions.egg-info/dependency_links.txt
> writing top-level names to extensions.egg-info/top_level.txt
> /home/mwaliman/workspace/InExtremIS/env/lib/python3.6/site-packages/torch/utils/cpp_extension.py:352: UserWarning: Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils backend.
>   warnings.warn(msg.format('we could not find ninja.'))
> reading manifest file 'extensions.egg-info/SOURCES.txt'
> writing manifest file 'extensions.egg-info/SOURCES.txt'
> installing library code to build/bdist.linux-x86_64/egg
> running install_lib
> running build_ext
> creating build/bdist.linux-x86_64/egg
> copying build/lib.linux-x86_64-3.6/HT_opp.cpython-36m-x86_64-linux-gnu.so -> build/bdist.linux-x86_64/egg
> creating stub loader for HT_opp.cpython-36m-x86_64-linux-gnu.so
> byte-compiling build/bdist.linux-x86_64/egg/HT_opp.py to HT_opp.cpython-36.pyc
> creating build/bdist.linux-x86_64/egg/EGG-INFO
> copying extensions.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
> copying extensions.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
> copying extensions.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
> copying extensions.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
> writing build/bdist.linux-x86_64/egg/EGG-INFO/native_libs.txt
> zip_safe flag not set; analyzing archive contents...
> __pycache__.HT_opp.cpython-36: module references __file__
> creating 'dist/extensions-0.0.0-py3.6-linux-x86_64.egg' and adding 'build/bdist.linux-x86_64/egg' to it
> removing 'build/bdist.linux-x86_64/egg' (and everything under it)
> Processing extensions-0.0.0-py3.6-linux-x86_64.egg
> removing '/home/mwaliman/.local/lib/python3.6/site-packages/extensions-0.0.0-py3.6-linux-x86_64.egg' (and everything under it)
> creating /home/mwaliman/.local/lib/python3.6/site-packages/extensions-0.0.0-py3.6-linux-x86_64.egg
> Extracting extensions-0.0.0-py3.6-linux-x86_64.egg to /home/mwaliman/.local/lib/python3.6/site-packages
> 
> Installed /home/mwaliman/.local/lib/python3.6/site-packages/extensions-0.0.0-py3.6-linux-x86_64.egg
> Processing dependencies for extensions==0.0.0
> Finished processing dependencies for extensions==0.0.0

**Comment by mwaliman** [comment]
Thank you! I hadn't yet run setup.py in /Permutohedral_attention_module/PAM_cuda/ yet.
